# Generated by Django 4.0.4 on 2022-05-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Alcohol'), (2, 'Soft drink'), (3, 'Fruit'), (4, 'Spice')])),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DrinkRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinkName', models.CharField(max_length=100)),
                ('preparation', models.CharField(max_length=1000)),
                ('ingredients', models.ManyToManyField(to='shakerApp.ingredients')),
            ],
        ),
    ]
