# Generated by Django 4.0.4 on 2022-05-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakerApp', '0002_type_alter_ingredients_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='type',
            field=models.IntegerField(choices=[(1, 'Soft drink'), (2, 'Alcohol'), (3, 'Fruit'), (4, 'Spice')]),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
