# Generated by Django 4.0.4 on 2022-05-26 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shakerApp', '0003_alter_ingredients_type_delete_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'Soft drink'), (2, 'Alcohol'), (3, 'Fruit'), (4, 'Spice')])),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shakerApp.type')),
            ],
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shakerApp.type'),
        ),
    ]
