# Generated by Django 4.0.4 on 2022-05-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakerApp', '0005_alter_ingredients_type_delete_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkrecipe',
            name='utensil',
            field=models.IntegerField(choices=[(1, 'Glass'), (2, 'Shaker')], default=0),
        ),
    ]
