# Generated by Django 4.0.4 on 2022-05-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakerApp', '0007_alter_drinkrecipe_preparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkrecipe',
            name='preparation',
            field=models.CharField(max_length=1000),
        ),
    ]
