# Generated by Django 4.0.4 on 2022-05-31 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shakerApp', '0008_alter_drinkrecipe_preparation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinkrecipe',
            old_name='drinkName',
            new_name='name',
        ),
    ]
