# Generated by Django 4.0.4 on 2022-06-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakerApp', '0010_drinkrecipe_drinkimage_ingredients_ingredientimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkrecipe',
            name='drinkImage',
            field=models.ImageField(default='./static/shakerApp/media/no-photo.png', upload_to='./static/shakerApp/media/no-photo.png'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ingredientImage',
            field=models.ImageField(default='./static/shakerApp/media/no-photo.png', upload_to='./static/shakerApp/media/'),
        ),
    ]
