# Generated by Django 4.0.4 on 2022-06-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakerApp', '0016_rename_drinkimage_drinkrecipe_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkrecipe',
            name='image',
            field=models.ImageField(default='media/no-photo.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='image',
            field=models.ImageField(default='media/no-photo.png', upload_to=''),
        ),
    ]
