# Generated by Django 4.0.4 on 2022-06-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakerApp', '0017_alter_drinkrecipe_image_alter_ingredients_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkrecipe',
            name='image',
            field=models.ImageField(default='static/media/no-photo.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='image',
            field=models.ImageField(default='static/media/no-photo.png', upload_to=''),
        ),
    ]
